CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lookup_id TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL DEFAULT 'Guest',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_lookup_id ON users(lookup_id);
