name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --build-arg RUN_ID=${{ github.run_id }} -t guess_rs .

      - name: Save Docker Image
        run: |
          docker save guess_rs -o ./guess_rs.tar
          ls -lh ./guess_rs.tar

      - name: Upload Docker Image to DigitalOcean
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_IP_ADDR }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "./guess_rs.tar"
          target: "~/guess_rs"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_IP_ADDR }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker load -i ~/funbanking/funbanking.tar
            rm ~/funbanking/funbanking.tar

            docker rm -f funbanking_container || true

            cd ~/funbanking

            docker run -d \
                -p 8080:8080 \
                -v $(pwd)/database.db:/app/database.db \
                -v $(pwd)/database.db-shm:/app/database.db-shm \
                -v $(pwd)/database.db-wal:/app/database.db-wal \
                -v $(pwd)/ip_db.BIN:/app/ip_db.BIN \
                -v $(pwd)/.env:/app/.env \
                -e APP_VERSION=${{ github.run_id }} \
                -e APP_PORT=8080 \
                --name funbanking_container funbanking  
